name: NPM Format Check

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened, ready_for_review, edited]
  schedule:
    - cron: '16 19 * * *'

jobs:
  format-check:
    if: ${{ github.event_name != 'pull_request' || (github.event.pull_request.head.repo.full_name == github.repository && contains(github.event.pull_request.labels.*.name, 'release')) }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v7

      - name: "Use Node.js"
        uses: actions/setup-node@v7
        with:
          node-version: '20.x'

      - name: "Install npm dependencies"
        run: npm ci

      - name: "Check code formatting"
        run: npm run format:check 