name: PHP Linting
on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened, ready_for_review, edited]
  schedule:
    - cron: '11 21 * * *'
permissions:
  contents: read
jobs:
  pint:
    if: ${{ github.event_name != 'pull_request' || (github.event.pull_request.head.repo.full_name == github.repository && contains(github.event.pull_request.labels.*.name, 'release')) }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v7

      - name: "Check code style"
        uses: aglipanci/laravel-pint-action@2.6
        with:
          configPath: "pint.json"
